spring:
  application:
    name: sensorservice
  profiles:
    active: dev
#  datasource:
#    url: jdbc:postgresql://localhost:5432/strommeister
#    username: postgres
#    password: dev
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
